name: Task Form
description: A form to report a task
title: "[🧰]: "
labels: ["enhancement", "triage"]
projects: ["dragonstone-org/4"]
assignees:
  - dragons
body:
  - type: markdown
    attributes:
      value: |
        ## Task Form
        Please fill out the form below to report a task.         
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@returngis.net
    validations:
      required: false
  - type: textarea
    id: what-do-you-need
    attributes:
      label: What do you need?
      description: Please describe the task you need help with.
      placeholder: I new a cool feature that does X
      value: "I need a cool feature that does X"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this task?
      options:
        - Low
        - Medium
        - High
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the task.
      render: markdown  
